import { ComponentMeta } from './types'

/** 项目根目录，用于拼接源码绝对路径 */
const PROJECT_ROOT = 'c:\\000\\code\\design'

/**
 * 示例组件数据集
 * 实际项目中会通过 scan-components.ts 自动扫描 library/ 目录生成
 */
export const components: ComponentMeta[] = [
  // ===== button =====
  {
    id: 'react-button-glow',
    name: '发光按钮',
    techStack: 'react',
    category: 'button',
    tags: ['button', 'glow', 'animation', 'interactive', 'futuristic', 'cta'],
    dependencies: ['framer-motion'],
    fonts: ['Inter'],
    source: '21st.dev',
    sourceUrl: 'https://21st.dev/community/components/neon-glow-button',
    author: 'component-creator',
    createdAt: '2026-06-30',
    updatedAt: '2026-06-30',
    previewPath: `${PROJECT_ROOT}/library/react/button/glow/preview.tsx`,
    sourcePath: `${PROJECT_ROOT}/library/react/button/glow/index.tsx`,
    variants: [
      { name: 'cyan', file: 'variants/cyan.tsx', description: '青色发光变体' },
      { name: 'magenta', file: 'variants/magenta.tsx', description: '品红发光变体' },
      { name: 'amber', file: 'variants/amber.tsx', description: '琥珀发光变体' },
    ],
    card: {
      description: '悬停时产生柔和发光效果的按钮，边缘有渐变光晕，使用 framer-motion 实现流畅的交互反馈。适用于需要强调的主操作按钮。',
      props: [
        { name: 'color', type: 'string', defaultValue: "'#00f0ff'", description: '发光颜色' },
        { name: 'intensity', type: 'number', defaultValue: '1', description: '发光强度 (0-2)' },
        { name: 'children', type: 'ReactNode', description: '按钮内容' },
        { name: 'onClick', type: '() => void', description: '点击回调' },
      ],
      usageExample: `import { GlowButton } from '@/library/react/button/glow';\n\n<GlowButton color="#00f0ff" intensity={1.5}>\n  立即开始\n</GlowButton>`,
      applicableScenes: ['CTA 按钮', '主操作按钮', '强调性交互元素'],
    },
  },
  {
    id: 'react-button-gradient',
    name: '渐变边框按钮',
    techStack: 'react',
    category: 'button',
    tags: ['button', 'gradient', 'border', 'animated', 'modern', 'cta'],
    dependencies: ['framer-motion'],
    source: 'Aceternity UI',
    createdAt: '2026-06-29',
    updatedAt: '2026-06-29',
    previewPath: `${PROJECT_ROOT}/library/react/button/gradient-border/preview.tsx`,
    sourcePath: `${PROJECT_ROOT}/library/react/button/gradient-border/index.tsx`,
    card: {
      description: '带有动画渐变边框的按钮，边框颜色持续流动变化。悬停时光效加速，点击时有涟漪反馈。',
      props: [
        { name: 'colors', type: 'string[]', defaultValue: "['#00f0ff', '#7b61ff']", description: '渐变颜色数组' },
        { name: 'borderWidth', type: 'number', defaultValue: '2', description: '边框宽度 (px)' },
        { name: 'duration', type: 'number', defaultValue: '3', description: '动画周期 (s)' },
        { name: 'children', type: 'ReactNode', description: '按钮内容' },
      ],
      usageExample: `import { GradientButton } from '@/library/react/button/gradient-border';\n\n<GradientButton colors={['#ff6b6b', '#feca57']}>\n  开始体验\n</GradientButton>`,
      applicableScenes: ['CTA 按钮', 'Landing Page', '产品介绍'],
    },
  },
  // ===== form =====
  {
    id: 'react-form-input-float',
    name: '浮动标签输入框',
    techStack: 'react',
    category: 'form',
    tags: ['input', 'form', 'float-label', 'minimal', 'clean', 'elegant'],
    dependencies: [],
    source: 'Magic UI',
    createdAt: '2026-06-28',
    updatedAt: '2026-06-28',
    previewPath: `${PROJECT_ROOT}/library/react/form/input-float/preview.tsx`,
    sourcePath: `${PROJECT_ROOT}/library/react/form/input-float/index.tsx`,
    card: {
      description: '标签在输入时浮动到顶部的输入框，纯 CSS 实现，无 JS 依赖。聚焦时有柔和的边框过渡动画。',
      props: [
        { name: 'label', type: 'string', description: '输入框标签' },
        { name: 'type', type: 'string', defaultValue: "'text'", description: '输入类型' },
        { name: 'value', type: 'string', description: '输入值（受控模式）' },
        { name: 'onChange', type: '(e: ChangeEvent) => void', description: '变更回调' },
      ],
      usageExample: `import { FloatInput } from '@/library/react/form/input-float';\n\n<FloatInput label="邮箱地址" type="email" />`,
      applicableScenes: ['登录表单', '注册表单', '设置面板'],
    },
  },
  {
    id: 'react-form-toggle-switch',
    name: '切换开关',
    techStack: 'react',
    category: 'form',
    tags: ['toggle', 'switch', 'input', 'boolean', 'minimal', 'accessible'],
    dependencies: ['framer-motion'],
    source: 'shadcn/ui',
    createdAt: '2026-06-10',
    updatedAt: '2026-06-10',
    previewPath: `${PROJECT_ROOT}/library/react/form/toggle-switch/preview.tsx`,
    sourcePath: `${PROJECT_ROOT}/library/react/form/toggle-switch/index.tsx`,
    card: {
      description: '无障碍切换开关组件，支持键盘操作和 ARIA 属性。带有流畅的滑动动画和状态颜色变化。',
      props: [
        { name: 'checked', type: 'boolean', defaultValue: 'false', description: '是否开启' },
        { name: 'onChange', type: '(checked: boolean) => void', description: '状态变更回调' },
        { name: 'disabled', type: 'boolean', defaultValue: 'false', description: '是否禁用' },
        { name: 'size', type: '"sm" | "md" | "lg"', defaultValue: '"md"', description: '尺寸' },
      ],
      usageExample: `import { Toggle } from '@/library/react/form/toggle-switch';\n\n<Toggle checked={enabled} onChange={setEnabled} />`,
      applicableScenes: ['设置面板', '功能开关', '偏好设置'],
    },
  },
  {
    id: 'react-form-select-combo',
    name: '下拉选择器',
    techStack: 'react',
    category: 'form',
    tags: ['select', 'dropdown', 'form', 'combobox', 'searchable', 'accessible'],
    dependencies: [],
    source: 'shadcn/ui',
    createdAt: '2026-06-09',
    updatedAt: '2026-06-09',
    previewPath: `${PROJECT_ROOT}/library/react/form/select-combo/preview.tsx`,
    sourcePath: `${PROJECT_ROOT}/library/react/form/select-combo/index.tsx`,
    card: {
      description: '支持下拉选择和搜索过滤的组合选择器，支持键盘导航、多选、分组显示。自定义渲染选项内容。',
      props: [
        { name: 'options', type: 'SelectOption[]', description: '选项数组' },
        { name: 'value', type: 'string | string[]', description: '当前选中值' },
        { name: 'onValueChange', type: '(v: string) => void', description: '变更回调' },
        { name: 'placeholder', type: 'string', defaultValue: "'请选择'", description: '占位文本' },
        { name: 'searchable', type: 'boolean', defaultValue: 'false', description: '是否可搜索' },
      ],
      usageExample: `import { Select } from '@/library/react/form/select-combo';\n\n<Select\n  options={[{ value: 'react', label: 'React' }, { value: 'vue', label: 'Vue' }]}\n  onValueChange={setFramework}\n  searchable\n/>`,
      applicableScenes: ['筛选面板', '设置表单', '数据录入'],
    },
  },
  // ===== navigation =====
  {
    id: 'react-navigation-sidebar',
    name: '侧边导航栏',
    techStack: 'react',
    category: 'navigation',
    tags: ['nav', 'sidebar', 'dashboard', 'navigation', 'collapsible'],
    dependencies: ['framer-motion'],
    source: 'shadcn/ui',
    createdAt: '2026-06-25',
    updatedAt: '2026-06-26',
    previewPath: `${PROJECT_ROOT}/library/react/navigation/sidebar/preview.tsx`,
    sourcePath: `${PROJECT_ROOT}/library/react/navigation/sidebar/index.tsx`,
    relatedComponents: ['react-navigation-topbar'],
    card: {
      description: '可折叠的侧边导航栏，支持多级菜单、图标模式切换。展开时显示文字，折叠时仅显示图标，带有平滑的过渡动画。',
      props: [
        { name: 'items', type: 'NavItem[]', description: '导航菜单项数组' },
        { name: 'collapsed', type: 'boolean', defaultValue: 'false', description: '是否折叠' },
        { name: 'onToggle', type: '() => void', description: '折叠切换回调' },
        { name: 'activeKey', type: 'string', description: '当前选中项 key' },
      ],
      usageExample: `import { SidebarNav } from '@/library/react/navigation/sidebar';\n\n<SidebarNav\n  items={[{ key: 'home', label: '首页', icon: HomeIcon }]}\n  collapsed={false}\n  activeKey="home"\n/>`,
      applicableScenes: ['管理后台', 'Dashboard', 'SaaS 应用'],
    },
  },
  {
    id: 'react-navigation-breadcrumb',
    name: '面包屑导航',
    techStack: 'react',
    category: 'navigation',
    tags: ['breadcrumb', 'nav', 'path', 'hierarchy', 'accessible'],
    dependencies: [],
    source: 'shadcn/ui',
    createdAt: '2026-06-14',
    updatedAt: '2026-06-14',
    previewPath: `${PROJECT_ROOT}/library/react/navigation/breadcrumb/preview.tsx`,
    sourcePath: `${PROJECT_ROOT}/library/react/navigation/breadcrumb/index.tsx`,
    card: {
      description: '层级面包屑导航组件，自动根据路由生成路径。支持自定义分隔符、省略折叠、下拉子菜单。',
      props: [
        { name: 'items', type: 'BreadcrumbItem[]', description: '面包屑项数组' },
        { name: 'separator', type: 'ReactNode', defaultValue: "'/'", description: '分隔符' },
        { name: 'maxItems', type: 'number', defaultValue: '5', description: '最大显示数量，超出折叠' },
      ],
      usageExample: `import { Breadcrumb } from '@/library/react/navigation/breadcrumb';\n\n<Breadcrumb items={[\n  { label: '首页', href: '/' },\n  { label: '组件库', href: '/library' },\n  { label: '按钮' },\n]} />`,
      applicableScenes: ['后台管理', '文档站点', '多层级页面'],
    },
  },
  // ===== layout =====
  {
    id: 'html-layout-pricing-table',
    name: '价格对比表',
    techStack: 'html',
    category: 'layout',
    tags: ['pricing', 'table', 'comparison', 'business', 'cta', 'responsive'],
    dependencies: [],
    source: 'Tailwind UI',
    createdAt: '2026-06-12',
    updatedAt: '2026-06-12',
    previewPath: `${PROJECT_ROOT}/library/html/layout/pricing-table/preview.html`,
    sourcePath: `${PROJECT_ROOT}/library/html/layout/pricing-table/index.html`,
    relatedComponents: ['react-data-display-stats-card'],
    card: {
      description: '三栏价格对比表，支持推荐方案高亮、功能列表对比、CTA 按钮。响应式布局，移动端堆叠为单栏。',
      props: [],
      usageExample: `<!-- 复制 HTML 结构后修改价格和功能列表 -->`,
      applicableScenes: ['SaaS 定价页', '产品对比', '订阅页面'],
    },
  },
  {
    id: 'react-layout-grid-masonry',
    name: '瀑布流布局',
    techStack: 'react',
    category: 'layout',
    tags: ['grid', 'masonry', 'layout', 'responsive', 'gallery', 'waterfall'],
    dependencies: [],
    source: '21st.dev',
    createdAt: '2026-06-11',
    updatedAt: '2026-06-11',
    previewPath: `${PROJECT_ROOT}/library/react/layout/grid-masonry/preview.tsx`,
    sourcePath: `${PROJECT_ROOT}/library/react/layout/grid-masonry/index.tsx`,
    card: {
      description: 'CSS columns 实现的瀑布流布局组件，自动适配不同高度的内容卡片。支持动态列数和间距调整。',
      props: [
        { name: 'columns', type: 'number', defaultValue: '3', description: '列数' },
        { name: 'gap', type: 'number', defaultValue: '16', description: '间距 (px)' },
        { name: 'children', type: 'ReactNode', description: '内容子元素' },
      ],
      usageExample: `import { MasonryGrid } from '@/library/react/layout/grid-masonry';\n\n<MasonryGrid columns={3} gap={16}>\n  {items.map(item => <Card key={item.id} />)}\n</MasonryGrid>`,
      applicableScenes: ['图片画廊', '作品集', '内容聚合页'],
    },
  },
  // ===== data-display =====
  {
    id: 'react-data-display-stats-card',
    name: '统计卡片',
    techStack: 'react',
    category: 'data-display',
    tags: ['card', 'stats', 'dashboard', 'data', 'metric', 'number'],
    dependencies: ['framer-motion'],
    source: 'Magic UI',
    createdAt: '2026-06-24',
    updatedAt: '2026-06-24',
    previewPath: `${PROJECT_ROOT}/library/react/data-display/stats-card/preview.tsx`,
    sourcePath: `${PROJECT_ROOT}/library/react/data-display/stats-card/index.tsx`,
    card: {
      description: '数据统计展示卡片，数字带有计数动画。支持趋势指示（上升/下降）、迷你图表区域、自定义图标。',
      props: [
        { name: 'title', type: 'string', description: '统计标题' },
        { name: 'value', type: 'number', description: '统计数值' },
        { name: 'trend', type: '"up" | "down" | "flat"', description: '趋势方向' },
        { name: 'change', type: 'string', description: '变化百分比文本' },
      ],
      usageExample: `import { StatsCard } from '@/library/react/data-display/stats-card';\n\n<StatsCard title="活跃用户" value={12847} trend="up" change="+12.5%" />`,
      applicableScenes: ['Dashboard', '数据面板', '管理后台'],
    },
  },
  // ===== feedback =====
  {
    id: 'react-feedback-toast',
    name: '消息通知',
    techStack: 'react',
    category: 'feedback',
    tags: ['toast', 'notification', 'message', 'alert', 'feedback'],
    dependencies: ['framer-motion'],
    source: 'sonner',
    createdAt: '2026-06-08',
    updatedAt: '2026-06-08',
    previewPath: `${PROJECT_ROOT}/library/react/feedback/toast/preview.tsx`,
    sourcePath: `${PROJECT_ROOT}/library/react/feedback/toast/index.tsx`,
    card: {
      description: '轻量消息通知组件，支持 success / error / warning / info 四种类型。自动消失、可手动关闭，支持堆叠显示。',
      props: [
        { name: 'type', type: '"success" | "error" | "warning" | "info"', defaultValue: '"info"', description: '通知类型' },
        { name: 'title', type: 'string', description: '标题' },
        { name: 'description', type: 'string', description: '描述文本' },
        { name: 'duration', type: 'number', defaultValue: '4000', description: '自动消失时间 (ms)' },
      ],
      usageExample: `import { toast } from '@/library/react/feedback/toast';\n\ntoast.success('保存成功', { description: '组件已入库' });`,
      applicableScenes: ['操作反馈', '系统通知', '表单提交结果'],
    },
  },
  {
    id: 'html-feedback-modal',
    name: '模态对话框',
    techStack: 'html',
    category: 'feedback',
    tags: ['modal', 'dialog', 'overlay', 'accessible', 'css-only'],
    dependencies: [],
    source: 'CodePen',
    createdAt: '2026-06-18',
    updatedAt: '2026-06-18',
    previewPath: `${PROJECT_ROOT}/library/html/feedback/modal/preview.html`,
    sourcePath: `${PROJECT_ROOT}/library/html/feedback/modal/index.html`,
    card: {
      description: '纯 CSS + 少量 JS 实现的模态对话框，支持焦点陷阱、ESC 关闭、点击遮罩关闭。使用 :target 伪类或 dialog 元素实现。',
      props: [],
      usageExample: `<!-- 直接在 HTML 中使用 -->\n<dialog id="my-modal">\n  <h2>标题</h2>\n  <p>内容</p>\n  <button onclick="this.closest('dialog').close()">关闭</button>\n</dialog>`,
      applicableScenes: ['确认操作', '表单弹窗', '信息展示'],
    },
  },
  // ===== effects =====
  {
    id: 'react-effects-hover-tilt',
    name: '悬停倾斜卡片',
    techStack: 'react',
    category: 'effects',
    tags: ['hover', 'tilt', '3d', 'interactive', 'parallax', 'card'],
    dependencies: ['framer-motion'],
    source: '21st.dev',
    createdAt: '2026-06-22',
    updatedAt: '2026-06-22',
    previewPath: `${PROJECT_ROOT}/library/react/effects/hover-tilt/preview.tsx`,
    sourcePath: `${PROJECT_ROOT}/library/react/effects/hover-tilt/index.tsx`,
    variants: [
      { name: 'subtle', file: 'variants/subtle.tsx', description: '微弱倾斜' },
      { name: 'extreme', file: 'variants/extreme.tsx', description: '大幅倾斜' },
    ],
    card: {
      description: '鼠标悬停时卡片产生 3D 倾斜效果，带有透视变换和光泽叠加。基于鼠标位置计算倾斜角度，带来沉浸式的交互体验。',
      props: [
        { name: 'maxTilt', type: 'number', defaultValue: '15', description: '最大倾斜角度 (deg)' },
        { name: 'glare', type: 'boolean', defaultValue: 'true', description: '是否显示光泽效果' },
        { name: 'children', type: 'ReactNode', description: '卡片内容' },
      ],
      usageExample: `import { TiltCard } from '@/library/react/effects/hover-tilt';\n\n<TiltCard maxTilt={20} glare>\n  <img src="/preview.jpg" alt="Preview" />\n</TiltCard>`,
      applicableScenes: ['产品展示', '作品集', '特性介绍'],
    },
  },
  {
    id: 'react-effects-scroll-reveal',
    name: '滚动渐入效果',
    techStack: 'react',
    category: 'effects',
    tags: ['scroll', 'reveal', 'animation', 'intersection', 'fade'],
    dependencies: ['framer-motion'],
    source: 'Framer Motion 官方示例',
    createdAt: '2026-06-20',
    updatedAt: '2026-06-20',
    previewPath: `${PROJECT_ROOT}/library/react/effects/scroll-reveal/preview.tsx`,
    sourcePath: `${PROJECT_ROOT}/library/react/effects/scroll-reveal/index.tsx`,
    card: {
      description: '基于 IntersectionObserver 的滚动渐入效果组件。元素在进入视口时触发动画，支持多种预设动画模式。',
      props: [
        { name: 'animation', type: '"fade-up" | "fade-left" | "fade-right" | "scale"', defaultValue: '"fade-up"', description: '动画类型' },
        { name: 'delay', type: 'number', defaultValue: '0', description: '延迟时间 (ms)' },
        { name: 'duration', type: 'number', defaultValue: '0.6', description: '动画时长 (s)' },
        { name: 'threshold', type: 'number', defaultValue: '0.1', description: '触发阈值 (0-1)' },
      ],
      usageExample: `import { ScrollReveal } from '@/library/react/effects/scroll-reveal';\n\n<ScrollReveal animation="fade-up" delay={200}>\n  <Section />\n</ScrollReveal>`,
      applicableScenes: ['长页面', 'Landing Page', '内容展示'],
    },
  },
  {
    id: 'html-effects-particle-bg',
    name: '粒子背景',
    techStack: 'html',
    category: 'effects',
    tags: ['particles', 'background', 'canvas', 'animation', 'ambient'],
    dependencies: [],
    source: 'CodePen',
    createdAt: '2026-06-15',
    updatedAt: '2026-06-15',
    previewPath: `${PROJECT_ROOT}/library/html/effects/particle-bg/preview.html`,
    sourcePath: `${PROJECT_ROOT}/library/html/effects/particle-bg/index.html`,
    card: {
      description: 'Canvas 实现的轻量粒子背景效果。粒子随机漂浮，鼠标靠近时产生排斥效果。性能优化良好，60fps 稳定运行。',
      props: [],
      usageExample: `<!-- 在页面底部引入 -->\n<canvas id="particles"></canvas>\n<script src="particles.js"></script>`,
      applicableScenes: ['Hero 背景', 'Landing Page', '科技感页面'],
    },
  },
  {
    id: 'react-effects-magnetic-button',
    name: '磁吸按钮',
    techStack: 'react',
    category: 'effects',
    tags: ['magnetic', 'button', 'hover', 'interactive', 'playful'],
    dependencies: ['framer-motion'],
    source: '21st.dev',
    createdAt: '2026-06-05',
    updatedAt: '2026-06-05',
    previewPath: `${PROJECT_ROOT}/library/react/effects/magnetic-button/preview.tsx`,
    sourcePath: `${PROJECT_ROOT}/library/react/effects/magnetic-button/index.tsx`,
    relatedComponents: ['react-button-glow'],
    card: {
      description: '鼠标靠近时按钮会被"吸引"向鼠标方向移动的交互效果。移开后按钮弹回原位，使用 spring 物理动画。',
      props: [
        { name: 'strength', type: 'number', defaultValue: '0.3', description: '磁吸强度 (0-1)' },
        { name: 'radius', type: 'number', defaultValue: '150', description: '磁吸作用范围 (px)' },
        { name: 'children', type: 'ReactNode', description: '按钮内容' },
      ],
      usageExample: `import { MagneticButton } from '@/library/react/effects/magnetic-button';\n\n<MagneticButton strength={0.4} radius={200}>\n  探索更多\n</MagneticButton>`,
      applicableScenes: ['CTA 按钮', '导航按钮', '趣味交互'],
    },
  },
  // ===== 3d =====
  {
    id: 'react-3d-scene-parallax',
    name: '3D 视差场景',
    techStack: 'react',
    category: '3d',
    tags: ['3d', 'parallax', 'three.js', 'scene', 'perspective', 'scroll'],
    dependencies: ['three', '@react-three/fiber'],
    source: 'Aceternity UI',
    createdAt: '2026-06-01',
    updatedAt: '2026-06-01',
    previewPath: `${PROJECT_ROOT}/library/react/3d/scene-parallax/preview.tsx`,
    sourcePath: `${PROJECT_ROOT}/library/react/3d/scene-parallax/index.tsx`,
    variants: [
      { name: 'subtle', file: 'variants/subtle.tsx', description: '轻微视差' },
    ],
    card: {
      description: '基于 Three.js 和 React Three Fiber 的 3D 视差滚动场景，多层元素以不同速度响应鼠标移动和滚动，营造深度感。支持自定义 3D 模型和光照。',
      props: [
        { name: 'intensity', type: 'number', defaultValue: '0.5', description: '视差强度 (0-1)' },
        { name: 'layers', type: 'ReactNode[]', description: '视差层内容' },
        { name: 'fov', type: 'number', defaultValue: '75', description: '相机视场角' },
      ],
      usageExample: `import { ParallaxScene } from '@/library/react/3d/scene-parallax';\n\n<ParallaxScene intensity={0.6}>\n  <Layer>背景层</Layer>\n  <Layer>前景层</Layer>\n</ParallaxScene>`,
      applicableScenes: ['产品展示', '品牌故事', '沉浸式页面'],
    },
  },
]

/** 标签全集（用于标签云 / 筛选下拉） */
export function getAllTags(): string[] {
  const tagSet = new Set<string>()
  components.forEach(c => c.tags.forEach(t => tagSet.add(t)))
  return Array.from(tagSet).sort()
}

/** 按分类获取筛选计数 */
export function getFilterCounts() {
  const counts: Record<string, number> = {}
  components.forEach(c => {
    counts[`cat:${c.category}`] = (counts[`cat:${c.category}`] || 0) + 1
  })
  return counts
}
